---
# Installs the Apache tomcat agent

- name: Install OpenAM tomcat Agent dir. This is the master template dir
  unarchive: dest="{{install_root}}" copy=no src="{{staging_dir}}/tomcat_agent.zip"
  
- name: Copy agent response file 
  template: src=agentresponse.txt dest={{agent_instance_dir}}/{{tomcat_instance}}-response.txt
 
#- name: Create agent instance dir
#  command: creates={{agent_instance_dir}} /bin/cp -r {{agent_home}} {{agent_instance_dir}}
  
- name: create password file
  copy: src=agentpw dest={{agent_instance_dir}}

- name: create agent config file
  copy: src=agent-config dest={{agent_instance_dir}}
  
#- name: Copy license agreement so we don't get prompted
#  copy: src=license.log dest={{agent_instance_dir}}/data

# Not needed as we run as the fr user 
- name: Change ownership of agent files 
  file: path="{{j2ee_agents_home}}" owner="{{fr_user}}"  recurse=yes state=directory

- name: Stop tomcat 
  service: name="{{ tomcat_instance }}" state=stopped

- name: Create agent config in openam using ssoadm
  shell: "{{ install_root }}/ssoadmin/openam/bin/ssoadm create-agent --realm / --agentname {{ tomcat_instance }}  --agenttype J2EEAgent  --adminid amadmin --password-file {{ home_dir }}/etc/amadmin_pw --datafile {{ agent_instance_dir }}/agent-config"

- name: Run agentadmin 
  command: "runuser -l {{fr_user}} -c '{{agent_instance_dir}}/bin/agentadmin --acceptLicense --custom-install --useResponse {{agent_instance_dir}}/{{tomcat_instance}}-response.txt'"

- name: Create sample application
  command: "runuser -l {{fr_user}} -c 'cp {{agent_instance_dir}}/sampleapp/dist/agentsample.war {{ tomcat_instance_dir }}/webapps'"

- name: Start tomcat
  service: name={{ tomcat_instance }} state=started
  
