---
# This role installs common base sw pre-reqs for the ForgeRock stack  using apt

- apt_repository: repo='deb http://cdn.debian.net/debian wheezy-backports main' state=present

- apt: update_cache=yes cache_valid_time=3600

- apt_key: url='http://haproxy.debian.net/bernat.debian.org.gpg'

#- name: Install the build dependencies for all packages
#  apt:
#    pkg: tomcat8
#    state: build-dep

- name: Install base software
  apt: name={{item}} state=latest
  with_items:
    - zip
   # - wget
    - openjdk-8-jdk
  #  - tomcat8
  #  - tomcat8-admin
  #  - tomcat8-user
    - haproxy
    - apache2

- name: copy ports.conf with 1080 port set for apache
  copy: src=ports.conf dest=/etc/apache2/ports.conf owner=root group=root mode=0644
